import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '../globals.css';
import Providers from '@/providers';
import Header from '@/components/header';
import { NextIntlClientProvider, useMessages } from 'next-intl';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  params: {
    locale: string;
  };
  children: React.ReactNode;
}) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body suppressHydrationWarning={true} className={inter.className}>
        <Providers>
          <NextIntlClientProvider messages={messages}>
            <Header locale={locale} />
            <div className="container mx-auto px-4 max-w-6xl">{children}</div>
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
